theme: jekyll-theme-cayman
title: <b>QUANT</b>ities in <b>I</b>mages and <b>T</b>ext at <b>CLIC</b> Lab <br>(<b>QUANTIT-CLIC</b>)
description: "Numbers, Quantifiers, Proportions in Language and Vision<br>CLIC Lab (CIMeC), University of Trento<br><br><tt>quantit dot clic at gmail dot com</tt>"

# Exclude these files from your production _site
#exclude:

