theme: jekyll-theme-cayman
title: <b>QUANT</b>ities in Images and Text at CLIC Lab <br>(QUANTIT-CLIC)
description: "Numbers, Quantifiers, Proportions in Language and Vision<br>CLIC Lab (CIMeC), University of Trento<br>quantit dot clic at gmail dot com"

# Exclude these files from your production _site
#exclude:

