theme: jekyll-theme-cayman
title: QUANTities in Images and Text at CLIC Lab (QuantIT-CLIC)
description: "Projects on quantification in Language and Vision at CLIC Lab, University of Trento"

# Exclude these files from your production _site
#exclude:

