theme: jekyll-theme-cayman
title: QUANTities in Images and Text at CLIC Lab
(QuantIT-CLIC)
description: "Numbers, Quantifiers, Proportions in Language and Vision
@ CLIC Lab (CIMeC), University of Trento"

# Exclude these files from your production _site
#exclude:

