theme: jekyll-theme-cayman
title: QUANTities in Images and Text at CLIC Lab<br>(QuantIT-CLIC)
description: "Numbers, Quantifiers, Proportions in Language and Vision<br>CLIC Lab (CIMeC), University of Trento"

# Exclude these files from your production _site
#exclude:

